// Most Likely To — question library.
// Add your own! Copy a line, change the text/tags, keep the format.
// Fields: q=question, cat=category, tone, diff=difficulty, deb=debate 1-10, hum=humour 1-10
window.QUESTIONS = [
  {"q": "Most likely to trip over absolutely nothing in public.", "cat": "Everyday Life", "tone": "Funny", "diff": "Easy", "deb": 6, "hum": 8},
  {"q": "Most likely to talk to a pet like it's a coworker.", "cat": "Everyday Life", "tone": "Wholesome", "diff": "Easy", "deb": 5, "hum": 7},
  {"q": "Most likely to forget why they walked into a room.", "cat": "Everyday Life", "tone": "Funny", "diff": "Medium", "deb": 7, "hum": 7},
  {"q": "Most likely to have 40 browser tabs open right now.", "cat": "Everyday Life", "tone": "Random", "diff": "Medium", "deb": 7, "hum": 6},
  {"q": "Most likely to reheat the same coffee four times.", "cat": "Everyday Life", "tone": "Funny", "diff": "Medium", "deb": 6, "hum": 7},
  {"q": "Most likely to narrate their own life out loud.", "cat": "Everyday Life", "tone": "Chaotic", "diff": "Medium", "deb": 7, "hum": 8},
  {"q": "Most likely to keep a drawer full of random cables.", "cat": "Everyday Life", "tone": "Random", "diff": "Easy", "deb": 6, "hum": 6},
  {"q": "Most likely to secretly be a genius.", "cat": "Personality", "tone": "Clever", "diff": "Hard", "deb": 8, "hum": 5},
  {"q": "Most likely to stay calm in a total crisis.", "cat": "Personality", "tone": "Competitive", "diff": "Hard", "deb": 8, "hum": 4},
  {"q": "Most likely to overthink a one-word text.", "cat": "Personality", "tone": "Awkward", "diff": "Medium", "deb": 8, "hum": 7},
  {"q": "Most likely to befriend a complete stranger in five minutes.", "cat": "Personality", "tone": "Wholesome", "diff": "Medium", "deb": 7, "hum": 6},
  {"q": "Most likely to have a strong opinion about pineapple on pizza.", "cat": "Personality", "tone": "Funny", "diff": "Easy", "deb": 8, "hum": 7},
  {"q": "Most likely to argue a point they secretly agree with.", "cat": "Personality", "tone": "Clever", "diff": "Hard", "deb": 8, "hum": 6},
  {"q": "Most likely to cry at a commercial.", "cat": "Personality", "tone": "Cute", "diff": "Medium", "deb": 6, "hum": 7},
  {"q": "Most likely to organise the whole friend group.", "cat": "Friendships", "tone": "Wholesome", "diff": "Medium", "deb": 7, "hum": 5},
  {"q": "Most likely to remember everyone's birthday.", "cat": "Friendships", "tone": "Wholesome", "diff": "Medium", "deb": 6, "hum": 4},
  {"q": "Most likely to start a group chat no one asked for.", "cat": "Friendships", "tone": "Funny", "diff": "Medium", "deb": 7, "hum": 7},
  {"q": "Most likely to be the designated therapist of the group.", "cat": "Friendships", "tone": "Wholesome", "diff": "Medium", "deb": 7, "hum": 5},
  {"q": "Most likely to accidentally leave someone on read for a week.", "cat": "Friendships", "tone": "Awkward", "diff": "Medium", "deb": 7, "hum": 7},
  {"q": "Most likely to bring a plus-one no one has met.", "cat": "Friendships", "tone": "Chaotic", "diff": "Medium", "deb": 7, "hum": 7},
  {"q": "Most likely to become the favourite aunt or uncle.", "cat": "Family", "tone": "Wholesome", "diff": "Medium", "deb": 7, "hum": 6},
  {"q": "Most likely to start a debate at the dinner table.", "cat": "Family", "tone": "Chaotic", "diff": "Medium", "deb": 8, "hum": 7},
  {"q": "Most likely to be caught retelling an embarrassing family story.", "cat": "Family", "tone": "Funny", "diff": "Medium", "deb": 7, "hum": 8},
  {"q": "Most likely to be the one who fixes everything at family events.", "cat": "Family", "tone": "Wholesome", "diff": "Medium", "deb": 6, "hum": 4},
  {"q": "Most likely to inherit grandma's stubborn streak.", "cat": "Family", "tone": "Funny", "diff": "Medium", "deb": 7, "hum": 7},
  {"q": "Most likely to plan a surprise that gets accidentally revealed.", "cat": "Couples", "tone": "Awkward", "diff": "Medium", "deb": 7, "hum": 7},
  {"q": "Most likely to win every playful argument.", "cat": "Couples", "tone": "Competitive", "diff": "Medium", "deb": 8, "hum": 6},
  {"q": "Most likely to steal all the blankets.", "cat": "Couples", "tone": "Funny", "diff": "Easy", "deb": 6, "hum": 7},
  {"q": "Most likely to plan the entire holiday down to the minute.", "cat": "Couples", "tone": "Competitive", "diff": "Medium", "deb": 7, "hum": 5},
  {"q": "Most likely to say 'I'm not mad' while clearly being mad.", "cat": "Couples", "tone": "Funny", "diff": "Medium", "deb": 8, "hum": 8},
  {"q": "Most likely to fall for someone within a week.", "cat": "Dating", "tone": "Cute", "diff": "Medium", "deb": 7, "hum": 6},
  {"q": "Most likely to have a hilariously bad first date story.", "cat": "Dating", "tone": "Funny", "diff": "Medium", "deb": 7, "hum": 8},
  {"q": "Most likely to overthink whether to double-text.", "cat": "Dating", "tone": "Awkward", "diff": "Medium", "deb": 8, "hum": 7},
  {"q": "Most likely to charm the entire room without trying.", "cat": "Dating", "tone": "Clever", "diff": "Hard", "deb": 8, "hum": 6},
  {"q": "Most likely to keep it casual and mean it.", "cat": "Dating", "tone": "Random", "diff": "Hard", "deb": 7, "hum": 4},
  {"q": "Most likely to reply-all to the entire company by accident.", "cat": "Work", "tone": "Awkward", "diff": "Medium", "deb": 7, "hum": 8},
  {"q": "Most likely to become the boss one day.", "cat": "Work", "tone": "Competitive", "diff": "Hard", "deb": 8, "hum": 5},
  {"q": "Most likely to schedule a meeting that should've been an email.", "cat": "Work", "tone": "Funny", "diff": "Medium", "deb": 7, "hum": 7},
  {"q": "Most likely to take a 'quick break' that lasts an hour.", "cat": "Work", "tone": "Funny", "diff": "Medium", "deb": 7, "hum": 7},
  {"q": "Most likely to secretly run the whole office.", "cat": "Work", "tone": "Clever", "diff": "Hard", "deb": 8, "hum": 5},
  {"q": "Most likely to unmute at the worst possible moment.", "cat": "Work", "tone": "Awkward", "diff": "Medium", "deb": 7, "hum": 8},
  {"q": "Most likely to finish the test first and still get top marks.", "cat": "School", "tone": "Competitive", "diff": "Medium", "deb": 7, "hum": 4},
  {"q": "Most likely to get caught passing notes.", "cat": "School", "tone": "Funny", "diff": "Easy", "deb": 6, "hum": 7},
  {"q": "Most likely to become the teacher's favourite.", "cat": "School", "tone": "Random", "diff": "Medium", "deb": 7, "hum": 5},
  {"q": "Most likely to cram the entire night before an exam.", "cat": "School", "tone": "Funny", "diff": "Medium", "deb": 7, "hum": 6},
  {"q": "Most likely to ask the question everyone was thinking.", "cat": "School", "tone": "Clever", "diff": "Medium", "deb": 6, "hum": 5},
  {"q": "Most likely to survive on instant noodles for a semester.", "cat": "University", "tone": "Funny", "diff": "Medium", "deb": 6, "hum": 7},
  {"q": "Most likely to pull an all-nighter for no real reason.", "cat": "University", "tone": "Chaotic", "diff": "Medium", "deb": 7, "hum": 6},
  {"q": "Most likely to join every club in the first week.", "cat": "University", "tone": "Random", "diff": "Medium", "deb": 7, "hum": 6},
  {"q": "Most likely to become friends with a professor.", "cat": "University", "tone": "Wholesome", "diff": "Medium", "deb": 7, "hum": 5},
  {"q": "Most likely to lose their student ID three times a term.", "cat": "University", "tone": "Funny", "diff": "Easy", "deb": 6, "hum": 6},
  {"q": "Most likely to miss a flight while at the airport.", "cat": "Travel", "tone": "Funny", "diff": "Medium", "deb": 7, "hum": 8},
  {"q": "Most likely to make a friend on every trip.", "cat": "Travel", "tone": "Wholesome", "diff": "Medium", "deb": 7, "hum": 6},
  {"q": "Most likely to overpack for a weekend away.", "cat": "Travel", "tone": "Funny", "diff": "Easy", "deb": 6, "hum": 7},
  {"q": "Most likely to wander off and get gloriously lost.", "cat": "Travel", "tone": "Chaotic", "diff": "Medium", "deb": 7, "hum": 7},
  {"q": "Most likely to try the strangest food on the menu.", "cat": "Travel", "tone": "Random", "diff": "Medium", "deb": 7, "hum": 7},
  {"q": "Most likely to book a trip on a total whim.", "cat": "Travel", "tone": "Chaotic", "diff": "Medium", "deb": 7, "hum": 6},
  {"q": "Most likely to burn water while cooking.", "cat": "Food", "tone": "Funny", "diff": "Easy", "deb": 6, "hum": 8},
  {"q": "Most likely to order the same meal every single time.", "cat": "Food", "tone": "Funny", "diff": "Medium", "deb": 7, "hum": 6},
  {"q": "Most likely to finish everyone else's leftovers.", "cat": "Food", "tone": "Funny", "diff": "Medium", "deb": 7, "hum": 7},
  {"q": "Most likely to become a surprisingly good chef.", "cat": "Food", "tone": "Wholesome", "diff": "Medium", "deb": 7, "hum": 5},
  {"q": "Most likely to have strong feelings about how toast is buttered.", "cat": "Food", "tone": "Random", "diff": "Medium", "deb": 7, "hum": 7},
  {"q": "Most likely to eat dessert before dinner.", "cat": "Food", "tone": "Funny", "diff": "Easy", "deb": 6, "hum": 6},
  {"q": "Most likely to adopt every stray they meet.", "cat": "Pets", "tone": "Cute", "diff": "Medium", "deb": 6, "hum": 6},
  {"q": "Most likely to throw a birthday party for their pet.", "cat": "Pets", "tone": "Cute", "diff": "Medium", "deb": 6, "hum": 7},
  {"q": "Most likely to lose a staring contest with a cat.", "cat": "Pets", "tone": "Funny", "diff": "Easy", "deb": 6, "hum": 8},
  {"q": "Most likely to have a dog that's better trained than them.", "cat": "Pets", "tone": "Funny", "diff": "Medium", "deb": 7, "hum": 7},
  {"q": "Most likely to become unexpectedly rich.", "cat": "Money", "tone": "Competitive", "diff": "Hard", "deb": 8, "hum": 5},
  {"q": "Most likely to buy something they'll never use.", "cat": "Money", "tone": "Funny", "diff": "Medium", "deb": 7, "hum": 7},
  {"q": "Most likely to split a bill down to the exact penny.", "cat": "Money", "tone": "Funny", "diff": "Medium", "deb": 7, "hum": 6},
  {"q": "Most likely to win big and lose it all the same night.", "cat": "Money", "tone": "Chaotic", "diff": "Hard", "deb": 8, "hum": 7},
  {"q": "Most likely to still have their first ever payslip.", "cat": "Money", "tone": "Wholesome", "diff": "Medium", "deb": 6, "hum": 5},
  {"q": "Most likely to go in for one thing and leave with ten.", "cat": "Shopping", "tone": "Funny", "diff": "Easy", "deb": 6, "hum": 7},
  {"q": "Most likely to return something five minutes after buying it.", "cat": "Shopping", "tone": "Funny", "diff": "Medium", "deb": 6, "hum": 6},
  {"q": "Most likely to queue overnight for a launch.", "cat": "Shopping", "tone": "Chaotic", "diff": "Medium", "deb": 7, "hum": 6},
  {"q": "Most likely to have an abandoned online basket full of dreams.", "cat": "Shopping", "tone": "Funny", "diff": "Medium", "deb": 7, "hum": 7},
  {"q": "Most likely to still use a password from ten years ago.", "cat": "Technology", "tone": "Funny", "diff": "Medium", "deb": 6, "hum": 7},
  {"q": "Most likely to fix the WiFi by turning it off and on.", "cat": "Technology", "tone": "Random", "diff": "Easy", "deb": 6, "hum": 6},
  {"q": "Most likely to own a gadget they've never figured out.", "cat": "Technology", "tone": "Funny", "diff": "Medium", "deb": 7, "hum": 6},
  {"q": "Most likely to accidentally go live on camera.", "cat": "Technology", "tone": "Awkward", "diff": "Medium", "deb": 7, "hum": 8},
  {"q": "Most likely to become the family tech support forever.", "cat": "Technology", "tone": "Funny", "diff": "Medium", "deb": 7, "hum": 6},
  {"q": "Most likely to thank the AI just in case.", "cat": "AI", "tone": "Funny", "diff": "Medium", "deb": 7, "hum": 8},
  {"q": "Most likely to let a robot run their entire life.", "cat": "AI", "tone": "Random", "diff": "Hard", "deb": 8, "hum": 6},
  {"q": "Most likely to argue with a chatbot and lose.", "cat": "AI", "tone": "Funny", "diff": "Medium", "deb": 7, "hum": 8},
  {"q": "Most likely to name their smart speaker like a pet.", "cat": "AI", "tone": "Cute", "diff": "Medium", "deb": 6, "hum": 7},
  {"q": "Most likely to trust a GPS straight into a lake.", "cat": "AI", "tone": "Chaotic", "diff": "Medium", "deb": 7, "hum": 8},
  {"q": "Most likely to rage quit and then immediately rejoin.", "cat": "Gaming", "tone": "Funny", "diff": "Medium", "deb": 7, "hum": 7},
  {"q": "Most likely to be a secret gaming legend.", "cat": "Gaming", "tone": "Competitive", "diff": "Hard", "deb": 8, "hum": 5},
  {"q": "Most likely to blame the lag for everything.", "cat": "Gaming", "tone": "Funny", "diff": "Medium", "deb": 7, "hum": 7},
  {"q": "Most likely to stay up till sunrise for 'one more game'.", "cat": "Gaming", "tone": "Chaotic", "diff": "Medium", "deb": 7, "hum": 6},
  {"q": "Most likely to carry the whole team and never mention it.", "cat": "Gaming", "tone": "Competitive", "diff": "Medium", "deb": 7, "hum": 5},
  {"q": "Most likely to accidentally like a post from three years ago.", "cat": "Social Media", "tone": "Awkward", "diff": "Medium", "deb": 7, "hum": 8},
  {"q": "Most likely to go viral for something totally random.", "cat": "Social Media", "tone": "Chaotic", "diff": "Hard", "deb": 8, "hum": 7},
  {"q": "Most likely to post a photo and delete it in ten minutes.", "cat": "Social Media", "tone": "Funny", "diff": "Medium", "deb": 6, "hum": 6},
  {"q": "Most likely to have a secret second account.", "cat": "Social Media", "tone": "Random", "diff": "Hard", "deb": 8, "hum": 6},
  {"q": "Most likely to reply to every comment they get.", "cat": "Social Media", "tone": "Wholesome", "diff": "Medium", "deb": 6, "hum": 5},
  {"q": "Most likely to buy a gym membership and never go.", "cat": "Fitness", "tone": "Funny", "diff": "Easy", "deb": 6, "hum": 7},
  {"q": "Most likely to become weirdly good at one random sport.", "cat": "Fitness", "tone": "Random", "diff": "Medium", "deb": 7, "hum": 6},
  {"q": "Most likely to talk about running more than actually running.", "cat": "Fitness", "tone": "Funny", "diff": "Medium", "deb": 7, "hum": 7},
  {"q": "Most likely to attempt a backflip they can't do.", "cat": "Fitness", "tone": "Chaotic", "diff": "Medium", "deb": 7, "hum": 8},
  {"q": "Most likely to take a friendly game way too seriously.", "cat": "Sports", "tone": "Competitive", "diff": "Medium", "deb": 8, "hum": 7},
  {"q": "Most likely to celebrate a win like they won a final.", "cat": "Sports", "tone": "Funny", "diff": "Medium", "deb": 7, "hum": 7},
  {"q": "Most likely to be picked first for any team.", "cat": "Sports", "tone": "Competitive", "diff": "Medium", "deb": 7, "hum": 4},
  {"q": "Most likely to trash talk and then completely lose.", "cat": "Sports", "tone": "Savage", "diff": "Medium", "deb": 8, "hum": 8},
  {"q": "Most likely to know every word to a song they claim to hate.", "cat": "Music", "tone": "Funny", "diff": "Medium", "deb": 7, "hum": 7},
  {"q": "Most likely to become an accidental karaoke legend.", "cat": "Music", "tone": "Chaotic", "diff": "Medium", "deb": 7, "hum": 8},
  {"q": "Most likely to have the most embarrassing playlist.", "cat": "Music", "tone": "Funny", "diff": "Medium", "deb": 7, "hum": 8},
  {"q": "Most likely to start a band on a whim.", "cat": "Music", "tone": "Random", "diff": "Medium", "deb": 7, "hum": 6},
  {"q": "Most likely to cry to a song in the car.", "cat": "Music", "tone": "Cute", "diff": "Medium", "deb": 6, "hum": 6},
  {"q": "Most likely to fall asleep halfway through every film.", "cat": "Movies", "tone": "Funny", "diff": "Easy", "deb": 6, "hum": 7},
  {"q": "Most likely to spoil the ending without realising.", "cat": "Movies", "tone": "Awkward", "diff": "Medium", "deb": 7, "hum": 7},
  {"q": "Most likely to quote the same movie constantly.", "cat": "Movies", "tone": "Funny", "diff": "Medium", "deb": 7, "hum": 7},
  {"q": "Most likely to cry at an animated film.", "cat": "Movies", "tone": "Cute", "diff": "Medium", "deb": 6, "hum": 6},
  {"q": "Most likely to binge a whole series in one sitting.", "cat": "TV", "tone": "Funny", "diff": "Easy", "deb": 6, "hum": 6},
  {"q": "Most likely to have watched the same show ten times.", "cat": "TV", "tone": "Funny", "diff": "Medium", "deb": 7, "hum": 6},
  {"q": "Most likely to start a show just for background noise.", "cat": "TV", "tone": "Random", "diff": "Easy", "deb": 6, "hum": 5},
  {"q": "Most likely to argue about the best TV finale ever.", "cat": "TV", "tone": "Competitive", "diff": "Medium", "deb": 8, "hum": 6},
  {"q": "Most likely to still be packing as the taxi arrives.", "cat": "Holidays", "tone": "Funny", "diff": "Medium", "deb": 7, "hum": 7},
  {"q": "Most likely to plan a group trip and organise everyone.", "cat": "Holidays", "tone": "Wholesome", "diff": "Medium", "deb": 7, "hum": 5},
  {"q": "Most likely to fall asleep on the beach and burn.", "cat": "Holidays", "tone": "Funny", "diff": "Medium", "deb": 6, "hum": 7},
  {"q": "Most likely to buy the tackiest souvenir possible.", "cat": "Holidays", "tone": "Funny", "diff": "Medium", "deb": 7, "hum": 7},
  {"q": "Most likely to start playing Christmas songs in October.", "cat": "Christmas", "tone": "Funny", "diff": "Easy", "deb": 7, "hum": 7},
  {"q": "Most likely to give the most thoughtful gift.", "cat": "Christmas", "tone": "Wholesome", "diff": "Medium", "deb": 7, "hum": 5},
  {"q": "Most likely to fall asleep before the presents are opened.", "cat": "Christmas", "tone": "Funny", "diff": "Medium", "deb": 6, "hum": 7},
  {"q": "Most likely to win, and gloat about, the family board game.", "cat": "Christmas", "tone": "Competitive", "diff": "Medium", "deb": 8, "hum": 7},
  {"q": "Most likely to wear the most ridiculous festive jumper.", "cat": "Christmas", "tone": "Funny", "diff": "Easy", "deb": 6, "hum": 7},
  {"q": "Most likely to take a costume way too seriously.", "cat": "Halloween", "tone": "Chaotic", "diff": "Medium", "deb": 7, "hum": 7},
  {"q": "Most likely to get scared first in a haunted house.", "cat": "Halloween", "tone": "Funny", "diff": "Easy", "deb": 6, "hum": 8},
  {"q": "Most likely to still be finding fake cobwebs in July.", "cat": "Halloween", "tone": "Funny", "diff": "Medium", "deb": 6, "hum": 7},
  {"q": "Most likely to eat all the trick-or-treat sweets themselves.", "cat": "Halloween", "tone": "Funny", "diff": "Easy", "deb": 6, "hum": 7},
  {"q": "Most likely to plan the whole summer in a spreadsheet.", "cat": "Summer", "tone": "Competitive", "diff": "Medium", "deb": 7, "hum": 6},
  {"q": "Most likely to get sunburnt in the shade.", "cat": "Summer", "tone": "Funny", "diff": "Easy", "deb": 6, "hum": 8},
  {"q": "Most likely to jump in the water fully clothed.", "cat": "Summer", "tone": "Chaotic", "diff": "Medium", "deb": 7, "hum": 7},
  {"q": "Most likely to start a water fight out of nowhere.", "cat": "Summer", "tone": "Chaotic", "diff": "Easy", "deb": 6, "hum": 7},
  {"q": "Most likely to sing loudly at every red light.", "cat": "Driving", "tone": "Funny", "diff": "Easy", "deb": 6, "hum": 7},
  {"q": "Most likely to name their car.", "cat": "Driving", "tone": "Cute", "diff": "Easy", "deb": 6, "hum": 6},
  {"q": "Most likely to get lost with the GPS on.", "cat": "Driving", "tone": "Funny", "diff": "Medium", "deb": 7, "hum": 7},
  {"q": "Most likely to be the calmest driver in a traffic jam.", "cat": "Driving", "tone": "Wholesome", "diff": "Medium", "deb": 7, "hum": 4},
  {"q": "Most likely to insist they know a faster shortcut.", "cat": "Driving", "tone": "Competitive", "diff": "Medium", "deb": 8, "hum": 7},
  {"q": "Most likely to be the first one dancing.", "cat": "Parties", "tone": "Chaotic", "diff": "Easy", "deb": 7, "hum": 7},
  {"q": "Most likely to fall asleep on the sofa at a party.", "cat": "Parties", "tone": "Funny", "diff": "Easy", "deb": 6, "hum": 7},
  {"q": "Most likely to plan the whole party and forget to enjoy it.", "cat": "Parties", "tone": "Wholesome", "diff": "Medium", "deb": 7, "hum": 5},
  {"q": "Most likely to start the conga line.", "cat": "Parties", "tone": "Chaotic", "diff": "Easy", "deb": 6, "hum": 7},
  {"q": "Most likely to be found chatting to the pet all night.", "cat": "Parties", "tone": "Cute", "diff": "Medium", "deb": 6, "hum": 7},
  {"q": "Most likely to lose their friends and their phone.", "cat": "Festivals", "tone": "Chaotic", "diff": "Medium", "deb": 7, "hum": 7},
  {"q": "Most likely to know the way to every stage.", "cat": "Festivals", "tone": "Competitive", "diff": "Medium", "deb": 6, "hum": 5},
  {"q": "Most likely to make the entire campsite their friend.", "cat": "Festivals", "tone": "Wholesome", "diff": "Medium", "deb": 7, "hum": 6},
  {"q": "Most likely to wear glitter for a week afterwards.", "cat": "Festivals", "tone": "Funny", "diff": "Medium", "deb": 6, "hum": 7},
  {"q": "Most likely to forget the tent poles.", "cat": "Camping", "tone": "Funny", "diff": "Medium", "deb": 7, "hum": 7},
  {"q": "Most likely to be scared of every night-time noise.", "cat": "Camping", "tone": "Funny", "diff": "Easy", "deb": 6, "hum": 7},
  {"q": "Most likely to become the fire-starting expert.", "cat": "Camping", "tone": "Competitive", "diff": "Medium", "deb": 6, "hum": 5},
  {"q": "Most likely to bring way too much and use none of it.", "cat": "Camping", "tone": "Funny", "diff": "Medium", "deb": 7, "hum": 6},
  {"q": "Most likely to get lost on a clearly marked trail.", "cat": "Outdoors", "tone": "Funny", "diff": "Medium", "deb": 7, "hum": 7},
  {"q": "Most likely to name every bird they see.", "cat": "Outdoors", "tone": "Wholesome", "diff": "Medium", "deb": 6, "hum": 6},
  {"q": "Most likely to swim in freezing water for the story.", "cat": "Outdoors", "tone": "Chaotic", "diff": "Medium", "deb": 7, "hum": 7},
  {"q": "Most likely to survive a zombie apocalypse.", "cat": "Survival", "tone": "Competitive", "diff": "Hard", "deb": 8, "hum": 6},
  {"q": "Most likely to panic first in an emergency.", "cat": "Survival", "tone": "Funny", "diff": "Medium", "deb": 8, "hum": 7},
  {"q": "Most likely to build a shelter out of nothing.", "cat": "Survival", "tone": "Competitive", "diff": "Hard", "deb": 7, "hum": 5},
  {"q": "Most likely to share their last snack with everyone.", "cat": "Survival", "tone": "Wholesome", "diff": "Medium", "deb": 7, "hum": 5},
  {"q": "Most likely to get voted leader on a desert island.", "cat": "Survival", "tone": "Competitive", "diff": "Hard", "deb": 8, "hum": 5},
  {"q": "Most likely to be the chosen one in a fantasy quest.", "cat": "Fantasy", "tone": "Random", "diff": "Hard", "deb": 8, "hum": 6},
  {"q": "Most likely to befriend the dragon instead of fighting it.", "cat": "Fantasy", "tone": "Wholesome", "diff": "Medium", "deb": 7, "hum": 7},
  {"q": "Most likely to get lost in a magical forest.", "cat": "Fantasy", "tone": "Funny", "diff": "Medium", "deb": 7, "hum": 6},
  {"q": "Most likely to become the villain by accident.", "cat": "Fantasy", "tone": "Chaotic", "diff": "Hard", "deb": 8, "hum": 7},
  {"q": "Most likely to use invisibility for something petty.", "cat": "Superpowers", "tone": "Savage", "diff": "Medium", "deb": 8, "hum": 8},
  {"q": "Most likely to use time travel to fix an awkward moment.", "cat": "Superpowers", "tone": "Awkward", "diff": "Medium", "deb": 8, "hum": 7},
  {"q": "Most likely to use super strength to open jars.", "cat": "Superpowers", "tone": "Funny", "diff": "Easy", "deb": 6, "hum": 8},
  {"q": "Most likely to accidentally reveal their secret identity.", "cat": "Superpowers", "tone": "Chaotic", "diff": "Medium", "deb": 7, "hum": 7},
  {"q": "Most likely to use mind reading and immediately regret it.", "cat": "Superpowers", "tone": "Funny", "diff": "Medium", "deb": 8, "hum": 7},
  {"q": "Most likely to volunteer for a one-way trip to Mars.", "cat": "Space", "tone": "Chaotic", "diff": "Hard", "deb": 8, "hum": 6},
  {"q": "Most likely to name a star after themselves.", "cat": "Space", "tone": "Funny", "diff": "Medium", "deb": 6, "hum": 6},
  {"q": "Most likely to make first contact with aliens.", "cat": "Space", "tone": "Random", "diff": "Hard", "deb": 8, "hum": 6},
  {"q": "Most likely to get spacesick on a rocket.", "cat": "Space", "tone": "Funny", "diff": "Medium", "deb": 6, "hum": 7},
  {"q": "Most likely to predict the next big trend.", "cat": "Future", "tone": "Clever", "diff": "Hard", "deb": 8, "hum": 5},
  {"q": "Most likely to still be using ancient tech in 2050.", "cat": "Future", "tone": "Funny", "diff": "Medium", "deb": 7, "hum": 7},
  {"q": "Most likely to invent something that changes everything.", "cat": "Future", "tone": "Competitive", "diff": "Hard", "deb": 8, "hum": 5},
  {"q": "Most likely to live in a smart home that controls them.", "cat": "Future", "tone": "Chaotic", "diff": "Medium", "deb": 7, "hum": 7},
  {"q": "Most likely to still own a toy from childhood.", "cat": "Childhood", "tone": "Cute", "diff": "Medium", "deb": 6, "hum": 6},
  {"q": "Most likely to have been the class clown.", "cat": "Childhood", "tone": "Funny", "diff": "Medium", "deb": 7, "hum": 7},
  {"q": "Most likely to have had an imaginary friend.", "cat": "Childhood", "tone": "Cute", "diff": "Medium", "deb": 6, "hum": 6},
  {"q": "Most likely to have got stuck up a tree.", "cat": "Childhood", "tone": "Funny", "diff": "Medium", "deb": 6, "hum": 7},
  {"q": "Most likely to call for backup to assemble furniture.", "cat": "Adulting", "tone": "Funny", "diff": "Medium", "deb": 7, "hum": 7},
  {"q": "Most likely to get weirdly excited about a new appliance.", "cat": "Adulting", "tone": "Wholesome", "diff": "Medium", "deb": 6, "hum": 6},
  {"q": "Most likely to forget to reply to an important email.", "cat": "Adulting", "tone": "Awkward", "diff": "Medium", "deb": 7, "hum": 6},
  {"q": "Most likely to have a drawer that won't fully close.", "cat": "Adulting", "tone": "Funny", "diff": "Easy", "deb": 6, "hum": 6},
  {"q": "Most likely to celebrate paying a bill on time.", "cat": "Adulting", "tone": "Funny", "diff": "Medium", "deb": 6, "hum": 7},
  {"q": "Most likely to have a wildly specific morning routine.", "cat": "Habits", "tone": "Random", "diff": "Medium", "deb": 7, "hum": 6},
  {"q": "Most likely to snack while pretending to work.", "cat": "Habits", "tone": "Funny", "diff": "Medium", "deb": 6, "hum": 7},
  {"q": "Most likely to reread the same page five times.", "cat": "Habits", "tone": "Funny", "diff": "Medium", "deb": 6, "hum": 6},
  {"q": "Most likely to wave back at someone who wasn't waving at them.", "cat": "Embarrassing Moments", "tone": "Awkward", "diff": "Medium", "deb": 7, "hum": 8},
  {"q": "Most likely to call the teacher 'mum' by accident.", "cat": "Embarrassing Moments", "tone": "Awkward", "diff": "Easy", "deb": 6, "hum": 8},
  {"q": "Most likely to walk into a glass door confidently.", "cat": "Embarrassing Moments", "tone": "Funny", "diff": "Easy", "deb": 6, "hum": 8},
  {"q": "Most likely to trip going up the stairs.", "cat": "Embarrassing Moments", "tone": "Funny", "diff": "Easy", "deb": 6, "hum": 7},
  {"q": "Most likely to laugh at completely the wrong moment.", "cat": "Embarrassing Moments", "tone": "Awkward", "diff": "Medium", "deb": 7, "hum": 8},
  {"q": "Most likely to actually drink enough water.", "cat": "Good Habits", "tone": "Wholesome", "diff": "Easy", "deb": 6, "hum": 4},
  {"q": "Most likely to send a thank-you note.", "cat": "Good Habits", "tone": "Wholesome", "diff": "Medium", "deb": 6, "hum": 4},
  {"q": "Most likely to check in on a friend just because.", "cat": "Good Habits", "tone": "Wholesome", "diff": "Medium", "deb": 6, "hum": 4},
  {"q": "Most likely to leave things until the very last second.", "cat": "Bad Habits", "tone": "Funny", "diff": "Medium", "deb": 7, "hum": 6},
  {"q": "Most likely to start a task and get distracted halfway.", "cat": "Bad Habits", "tone": "Funny", "diff": "Medium", "deb": 7, "hum": 6},
  {"q": "Most likely to say 'five more minutes' ten times.", "cat": "Bad Habits", "tone": "Funny", "diff": "Easy", "deb": 6, "hum": 7},
  {"q": "Most likely to win a raffle they forgot they entered.", "cat": "Luck", "tone": "Random", "diff": "Medium", "deb": 7, "hum": 6},
  {"q": "Most likely to find money on the ground.", "cat": "Luck", "tone": "Random", "diff": "Easy", "deb": 6, "hum": 5},
  {"q": "Most likely to get the last seat on a packed train.", "cat": "Luck", "tone": "Random", "diff": "Medium", "deb": 6, "hum": 5},
  {"q": "Most likely to have the worst luck with weather.", "cat": "Luck", "tone": "Funny", "diff": "Medium", "deb": 6, "hum": 6},
  {"q": "Most likely to win a pub quiz single-handedly.", "cat": "Intelligence", "tone": "Competitive", "diff": "Medium", "deb": 8, "hum": 5},
  {"q": "Most likely to know a random fact for every situation.", "cat": "Intelligence", "tone": "Clever", "diff": "Medium", "deb": 7, "hum": 6},
  {"q": "Most likely to outsmart a trick question.", "cat": "Intelligence", "tone": "Clever", "diff": "Hard", "deb": 8, "hum": 5},
  {"q": "Most likely to read the manual before starting.", "cat": "Intelligence", "tone": "Clever", "diff": "Medium", "deb": 6, "hum": 5},
  {"q": "Most likely to turn a boring task into a whole project.", "cat": "Creativity", "tone": "Random", "diff": "Medium", "deb": 7, "hum": 6},
  {"q": "Most likely to come up with the wildest idea in the room.", "cat": "Creativity", "tone": "Chaotic", "diff": "Medium", "deb": 8, "hum": 7},
  {"q": "Most likely to make art out of literal rubbish.", "cat": "Creativity", "tone": "Wholesome", "diff": "Medium", "deb": 7, "hum": 6},
  {"q": "Most likely to write a song about the group chat.", "cat": "Creativity", "tone": "Funny", "diff": "Medium", "deb": 7, "hum": 7},
  {"q": "Most likely to take charge when no one else will.", "cat": "Leadership", "tone": "Competitive", "diff": "Hard", "deb": 8, "hum": 5},
  {"q": "Most likely to give a motivational speech out of nowhere.", "cat": "Leadership", "tone": "Chaotic", "diff": "Medium", "deb": 7, "hum": 7},
  {"q": "Most likely to be trusted with the group's money.", "cat": "Leadership", "tone": "Wholesome", "diff": "Medium", "deb": 8, "hum": 4},
  {"q": "Most likely to make a tough call under pressure.", "cat": "Leadership", "tone": "Competitive", "diff": "Hard", "deb": 8, "hum": 4},
  {"q": "Most likely to remember the tiniest detail you mentioned once.", "cat": "Relationships", "tone": "Wholesome", "diff": "Medium", "deb": 7, "hum": 5},
  {"q": "Most likely to give brutally honest advice.", "cat": "Relationships", "tone": "Savage", "diff": "Medium", "deb": 8, "hum": 7},
  {"q": "Most likely to be everyone's emergency contact.", "cat": "Relationships", "tone": "Wholesome", "diff": "Medium", "deb": 7, "hum": 5},
  {"q": "Most likely to hold a grudge over something tiny.", "cat": "Relationships", "tone": "Funny", "diff": "Medium", "deb": 8, "hum": 7},
  {"q": "Most likely to start a conga line at a funeral... wait, no.", "cat": "Random Chaos", "tone": "Chaotic", "diff": "Medium", "deb": 7, "hum": 8},
  {"q": "Most likely to do something dramatic just to see what happens.", "cat": "Random Chaos", "tone": "Chaotic", "diff": "Medium", "deb": 8, "hum": 7},
  {"q": "Most likely to press the big red button.", "cat": "Random Chaos", "tone": "Chaotic", "diff": "Easy", "deb": 7, "hum": 8},
  {"q": "Most likely to say yes to a dare they'll regret.", "cat": "Random Chaos", "tone": "Chaotic", "diff": "Medium", "deb": 7, "hum": 7},
  {"q": "Most likely to turn a quiet night into a wild story.", "cat": "Random Chaos", "tone": "Chaotic", "diff": "Medium", "deb": 8, "hum": 7},
  {"q": "Most likely to accidentally start a new trend.", "cat": "Random Chaos", "tone": "Chaotic", "diff": "Hard", "deb": 8, "hum": 6},
  {"q": "Most likely to apologise to a chair they bumped into.", "cat": "Personality", "tone": "Awkward", "diff": "Easy", "deb": 6, "hum": 8},
  {"q": "Most likely to have a comeback ready three hours too late.", "cat": "Personality", "tone": "Funny", "diff": "Medium", "deb": 7, "hum": 7},
  {"q": "Most likely to be the voice of reason at 2am.", "cat": "Personality", "tone": "Wholesome", "diff": "Medium", "deb": 7, "hum": 5},
  {"q": "Most likely to volunteer before hearing the full question.", "cat": "Personality", "tone": "Chaotic", "diff": "Medium", "deb": 7, "hum": 7},
  {"q": "Most likely to lose their keys inside their own house.", "cat": "Everyday Life", "tone": "Funny", "diff": "Easy", "deb": 6, "hum": 7},
  {"q": "Most likely to leave a voicemail no one listens to.", "cat": "Everyday Life", "tone": "Funny", "diff": "Medium", "deb": 6, "hum": 6},
  {"q": "Most likely to keep receipts they'll never need.", "cat": "Everyday Life", "tone": "Random", "diff": "Medium", "deb": 6, "hum": 5},
  {"q": "Most likely to say 'you too' at the worst moment.", "cat": "Everyday Life", "tone": "Awkward", "diff": "Easy", "deb": 7, "hum": 8},
  {"q": "Most likely to microwave something and forget about it.", "cat": "Food", "tone": "Funny", "diff": "Easy", "deb": 6, "hum": 6},
  {"q": "Most likely to double-dip and deny it.", "cat": "Food", "tone": "Savage", "diff": "Medium", "deb": 7, "hum": 8},
  {"q": "Most likely to have an emotional support snack.", "cat": "Food", "tone": "Cute", "diff": "Medium", "deb": 6, "hum": 6},
  {"q": "Most likely to have the messiest but most productive desk.", "cat": "Work", "tone": "Random", "diff": "Medium", "deb": 7, "hum": 6},
  {"q": "Most likely to send 'per my last email'.", "cat": "Work", "tone": "Savage", "diff": "Medium", "deb": 8, "hum": 7},
  {"q": "Most likely to volunteer to present and love it.", "cat": "Work", "tone": "Competitive", "diff": "Medium", "deb": 7, "hum": 5},
  {"q": "Most likely to fall asleep the second the plane takes off.", "cat": "Travel", "tone": "Funny", "diff": "Easy", "deb": 6, "hum": 6},
  {"q": "Most likely to argue with a map and lose.", "cat": "Travel", "tone": "Funny", "diff": "Medium", "deb": 7, "hum": 7},
  {"q": "Most likely to spend more time customising than playing.", "cat": "Gaming", "tone": "Funny", "diff": "Medium", "deb": 7, "hum": 6},
  {"q": "Most likely to fall for the same trap twice.", "cat": "Gaming", "tone": "Funny", "diff": "Medium", "deb": 7, "hum": 7},
  {"q": "Most likely to take fifty photos to post one.", "cat": "Social Media", "tone": "Funny", "diff": "Medium", "deb": 7, "hum": 6},
  {"q": "Most likely to leave a review for everything.", "cat": "Social Media", "tone": "Random", "diff": "Medium", "deb": 7, "hum": 6},
  {"q": "Most likely to bring up marriage on date two.", "cat": "Dating", "tone": "Awkward", "diff": "Medium", "deb": 8, "hum": 7},
  {"q": "Most likely to keep talking to fill an awkward silence.", "cat": "Dating", "tone": "Awkward", "diff": "Medium", "deb": 7, "hum": 7},
  {"q": "Most likely to lend money and never ask for it back.", "cat": "Money", "tone": "Wholesome", "diff": "Medium", "deb": 7, "hum": 4},
  {"q": "Most likely to haggle over something already cheap.", "cat": "Money", "tone": "Funny", "diff": "Medium", "deb": 7, "hum": 7},
  {"q": "Most likely to stretch dramatically and pull a muscle.", "cat": "Fitness", "tone": "Funny", "diff": "Medium", "deb": 6, "hum": 7},
  {"q": "Most likely to use flying just to skip traffic.", "cat": "Superpowers", "tone": "Funny", "diff": "Medium", "deb": 7, "hum": 7},
  {"q": "Most likely to trust a self-driving car completely.", "cat": "Future", "tone": "Random", "diff": "Medium", "deb": 7, "hum": 6},
  {"q": "Most likely to hum a jingle for the rest of the day.", "cat": "Music", "tone": "Funny", "diff": "Easy", "deb": 6, "hum": 6},
  {"q": "Most likely to still be there when the lights come on.", "cat": "Parties", "tone": "Chaotic", "diff": "Medium", "deb": 7, "hum": 7},
  {"q": "Most likely to accidentally invite too many people.", "cat": "Parties", "tone": "Chaotic", "diff": "Medium", "deb": 7, "hum": 7},
  {"q": "Most likely to talk in a silly voice to any animal.", "cat": "Pets", "tone": "Cute", "diff": "Easy", "deb": 6, "hum": 7},
  {"q": "Most likely to correct a fact no one asked about.", "cat": "Intelligence", "tone": "Savage", "diff": "Medium", "deb": 8, "hum": 7},
  {"q": "Most likely to redecorate a room at midnight.", "cat": "Creativity", "tone": "Chaotic", "diff": "Medium", "deb": 7, "hum": 7},
  {"q": "Most likely to own a plant they're determined not to kill.", "cat": "Adulting", "tone": "Wholesome", "diff": "Medium", "deb": 6, "hum": 6},
  {"q": "Most likely to check the fridge again hoping food appeared.", "cat": "Habits", "tone": "Funny", "diff": "Easy", "deb": 6, "hum": 7},
  {"q": "Most likely to keep hitting snooze until the last second.", "cat": "Habits", "tone": "Funny", "diff": "Easy", "deb": 6, "hum": 6},
  {"q": "Most likely to turn a quick catch-up into a five-hour chat.", "cat": "Friendships", "tone": "Wholesome", "diff": "Medium", "deb": 7, "hum": 6},
  {"q": "Most likely to be the one holding everyone's bags.", "cat": "Friendships", "tone": "Funny", "diff": "Medium", "deb": 6, "hum": 6},
  {"q": "Most likely to raise their hand for extra homework.", "cat": "School", "tone": "Funny", "diff": "Medium", "deb": 7, "hum": 6},
  {"q": "Most likely to eat something they definitely shouldn't.", "cat": "Survival", "tone": "Chaotic", "diff": "Medium", "deb": 7, "hum": 7},
  {"q": "Most likely to reply to a group chat at 4am with chaos.", "cat": "Random Chaos", "tone": "Chaotic", "diff": "Medium", "deb": 7, "hum": 7},
];
